### ISSUE TITLE
Guard Duty Organization Admin Account

### ISSUE THREAD

**Issue by beauknowssoftware** [candidpartners/terraform-provider-candidaws#6]
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/guardduty/enable-organization-admin-account.html

**Comment by sshearn** [comment]
FYI https://www.terraform.io/docs/providers/aws/r/guardduty_organization_admin_account.html

**Comment by beauknowssoftware** [comment]
Good find @sshearn !
